SHASApplication/SHASApplication/Controllers/ConfigureController.cs
using SHASApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SHASApplication.Controllers
{
    public class ConfigureController : Controller
    {
        //
        // GET: /Configure/

        private shasEntities db = new shasEntities();

        public ActionResult Index()
        {
            var devicesArray = db.devices.ToArray();

            device[] revDevicesArray = new device[7];

            int i = 0;
            foreach (var item in devicesArray) {
                if (i < 7) {
                    revDevicesArray[i] = devicesArray[i];
                }
                i++;
            }

            return View(revDevicesArray);
        }

    }
}

SHASApplication/SHASApplication/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHASApplication.Models;

namespace SHASApplication.Controllers
{
    public class DeviceController : Controller
    {
        private shasEntities db = new shasEntities();

        //
        // GET: /Device/

        public ActionResult Index()
        {
            return View(db.devices.ToList());
        }

        //
        // GET: /Device/Details/5

        public ActionResult Details(int id = 0)
        {
            device device = db.devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        //
        // GET: /Device/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Device/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(device device)
        {
            if (ModelState.IsValid)
            {
                db.devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(device);
        }

        //
        // GET: /Device/Edit/5

        public ActionResult Edit(int id = 0)
        {
            device device = db.devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        //
        // POST: /Device/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(device device)
        {
            shasEntities db1 = new shasEntities();
            device dv1 = new device();
            dv1 = db1.devices.Find(device.ID);
            if (ModelState.IsValid)
            {
                device.TimeStamp = dv1.TimeStamp;
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(device);
        }

        //
        // GET: /Device/Delete/5

        public ActionResult Delete(int id = 0)
        {
            device device = db.devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        //
        // POST: /Device/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            device device = db.devices.Find(id);
            db.devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SHASApplication/SHASApplication/Views/Configure/Index.cshtml
@model IEnumerable<SHASApplication.Models.device>

@{
    ViewBag.Title = "Configure";
}
@section HeadContent {
<style>
    .bordered {
        max-width:300px;
        border:1px solid #cc3;
        background: center no-repeat url('@Url.Content("~/Content/Kendo/shared/world-map.png")');
        height: 125px;
        float:left;
    }
</style>
}

<h2 style="float:left; ">Configure Devices</h2>
<p style="visibility:hidden; clear:both; float:left"></p>
@foreach (var item in Model) {
    if (item.DeviceStatus.Equals("ON")) 
    {
        @Html.Partial("_ConfigDeviceTileON", item);    
    } 
    else 
    { 
        @Html.Partial("_ConfigDeviceTileOFF", item);
    } 
}

<p style="visibility:hidden; clear:both; float:left"></p>
<div style="float:left; clear:both">
    <h2 style="float:left; clear:both">Configure Alerts</h2>
    <h3 style="float:left; clear:both">@Html.ActionLink("User Alerts", "Index", "ConfigureAlert")</h3>
    <h3 style="float:left; clear:both">@Html.ActionLink("Emergency Authorities", "Index", "ConfigEmergencyAuthorities")</h3>
</div>
<p style="visibility:hidden; clear:both; float:left"></p>
<div style="float:left; clear:both">
    <h2 style="float:left; clear:both">Manage Devices</h2>
    <h3 style="float:left; clear:both">@Html.ActionLink("Device List", "Index", "Device")</h3>
</div>